INSERT INTO tb_user (name, email, password) VALUES ('Bob Brown', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Ana Green', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');

INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);

INSERT INTO tb_genre(name) VALUES ('Comédia');
INSERT INTO tb_genre(name) VALUES ('Terror');
INSERT INTO tb_genre(name) VALUES ('Drama');
INSERT INTO tb_genre(name) VALUES ('Animação');

INSERT INTO tb_movie(img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://br.web.img3.acsta.net/pictures/21/08/10/12/37/3505433.jpges', 'Dune', 'A vida do jovem Paul Atreides (Timothée Chalamet) está prestes a mudar radicalmente. Após a visita de uma mulher misteriosa, ele é obrigado a deixar seu planeta natal para sobreviver ao ambiente árido e severo de Arrakis, o Planeta Deserto. Envolvido numa intrincada teia política e religiosa, Paul divide-se entre as obrigações de herdeiro e seu treinamento nas doutrinas secretas de uma antiga irmandade, que vê nele a esperança de realização de um plano urdido há séculos. Baseado no romance homônimo de Frank Herbert.', 'Duna', 2021, 3);
INSERT INTO tb_movie(img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://br.web.img3.acsta.net/pictures/21/06/22/22/19/1495362.jpgum', 'The Suicide Squad', 'Liderados por Sanguinário, Pacificador, Coronel Rick Flag, e pela psicopata favorita de todos, Arlequina, o Esquadrão Suicida está disposto a fazer qualquer coisa para escapar da prisão. Armados até os dentes e rastreados pela equipe de Amanda Waller, eles são jogados (literalmente) na remota ilha Corto Maltese, repleta de militantes adversários e forças de guerrilha. O grupo de supervilões busca destruição, mas basta um movimento errado para que acabem mortos.', 'O Esquadrão Suicida', 2021, 1);
INSERT INTO tb_movie(img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://br.web.img3.acsta.net/c_310_420/pictures/21/07/07/00/23/1802515.jpg', 'A Quiet Place Part II', 'Seguindo os acontecimentos mortais dentro de casa, a família Abbott precisa agora encarar o terror mundo afora, continuando a lutar para sobreviver em silêncio. Obrigados a se aventurar pelo desconhecido, eles rapidamente percebem que as criaturas que caçam pelo som não são as únicas ameaças que os observam pelo caminho de areia.', 'Um Lugar Silencioso - Parte II', 2021, 2);
INSERT INTO tb_movie(img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://www.themoviedb.org/t/p/w220_and_h330_face/9jPa6SlUYxPFMVZlEuceiPPAA15.jpg','Luca', 'Ambientado na bela Riviera Italiana, este longa-metragem da Disney e da Pixar acompanha as aventuras do garoto Luca durante um verão inesquecível repleto de macarronadas, gelatos e passeios incríveis de motoneta ao lado de seu novo amigo Alberto. Mas um grande segredo ameaça colocar fim à diversão: abaixo da superfície da água, eles são monstros marinhos!', 'Luca', 2021, 1);
INSERT INTO tb_movie(img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://www.themoviedb.org/t/p/w220_and_h330_face/69kPJaCFMXuZfbCrbDaYfMZbtJt.jpg', 'HEELS', 'Dois irmãos e rivais no ringue - um, ‘vilão’; o outro, ‘herói’ - lutam pelo legado de seu falecido pai no wrestling, disputando a atenção nacional na pequena cidade da Geórgia.', 'HELLS', 2021, 3);
INSERT INTO tb_movie(img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://www.themoviedb.org/t/p/w220_and_h330_face/c805OuxH4oMniHRVIvMwy1fvzzw.jpg', 'Cruella', 'Na Londres dos anos 70 em meio à revolução do punk rock, Estella, uma garota inteligente e criativa determinada a fazer um nome para si através de seus designs. Ela faz amizade com uma dupla de jovens ladrões e, juntos, constroem uma vida para si nas ruas de Londres. Um dia, o talento de Estella para a moda chama a atenção da Baronesa Von Hellman, uma lenda fashion que é devastadoramente chique e assustadora. Mas o relacionamento delas desencadeia um curso de eventos e revelações que farão com que Estella abrace seu lado rebelde e se torne a Cruella má, elegante e voltada para a vingança.', 'Cruela', 2021, 1);
INSERT INTO tb_movie(img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://www.themoviedb.org/t/p/w220_and_h330_face/kU0NbsUVoUMcYxoISmBCxFmgWYC.jpg', 'Space Jam: Um Novo Legado','O superastro do basquete LeBron James se junta à gangue Looney Tunes para derrotar o Goon Squad e salvar seu filho.','Space Jam: Um Novo Legado', 2021, 1);
INSERT INTO tb_movie(img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://www.themoviedb.org/t/p/w220_and_h330_face/yaX5hliSF1rwZ9WVNbUchndjFSb.jpg', 'Demon Slayer - Mugen Train: O Filme', 'Tanjiro Kamado, junto com Inosuke Hashibira, um garoto criado por javalis que usa uma cabeça de javali, e Zenitsu Agatsuma, um garoto assustado que revela seu verdadeiro poder quando dorme, embarca no Trem Infinito em uma nova missão com o Hashira de Fogo, Kyojuro Rengoku, para derrotar um demônio que tem atormentado o povo e matado os caçadores de oni que se opõem a ele!','Demon Slayer - Mugen Train: O Filme', 2021, 4);
INSERT INTO tb_movie(img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://www.themoviedb.org/t/p/w220_and_h330_face/2SoNcDen3geolOZzJMhsQL3Nk1X.jpg','Jolt: Fúria Fatal','Uma segurança de boate com um transtorno de controle de raiva meio fatal usa um colete revestido por eletrodos para se dar choques e reverter ao estado normal sempre que é tomada por uma fúria homicida. Quando o primeiro homem por quem ela se apaixona na vida é assassinado, sua sede de vingança alimenta uma caçada ao assassino, enquanto a polícia a investiga como principal suspeita.', 'Jolt: Fúria Fatal', 2021, 1);
INSERT INTO tb_movie(img_url, sub_title, synopsis, title, year, genre_id) VALUES ('https://www.themoviedb.org/t/p/w220_and_h330_face/8kOWDBK6XlPUzckuHDo3wwVRFwt.jpg','Rick e Morty','Rick é um velho mentalmente desequilibrado, mas cientificamente talentoso que se reconectou recentemente com sua família. Ele passa a maior parte do tempo envolvendo o jovem neto Morty em aventuras perigosas e estranhas no espaço e em universos alternativos. Compostos à vida familiar já instável de Morty, esses eventos causam muito sofrimento a Morty em casa e na escola.','Rick e Morty', 2013, 4);

INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Gostei muito do filme. Foi muito bom mesmo. Pena que durou pouco', 6, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Gostei muito do filme. Foi muito bom mesmo. Pena que durou pouco', 6, 2);